#+STARTUP: overview
#+TITLE: yukimacs
#+LANGUAGE: en
#+OPTIONS: num:nil
A GNU/Emacs config built from the ground up (no Spacemacs or Doom Emacs), heavily inspired by [[https://github.com/daedreth/UncleDavesEmacs/][Uncle Dave's Emacs]] and [[https://github.com/snackon/Witchmacs][Witchmacs]].

/If Vim expands your mind, Emacs blows it./

* Installing
Remove your current =~/.emacs= and =~/.emacs.d=.

=git clone https://github.com/pprobst/yukimacs ~/.emacs.d=

* =Org= mode
You might've heard of people that use Emacs just because of [[https://orgmode.org/][Org]] mode. Folks use it for a myriad of reasons; from simple note-taking to literate programming and computational notebooks. This configuration file itself is in Org mode, with small sections of Emacs Lisp.

#+begin_src emacs-lisp
  (require 'org-tempo)
  (add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))

  (use-package org
      :config
      (add-hook 'org-mode-hook 'org-indent-mode)
      (add-hook 'org-mode-hook
                '(lambda ()
                   (visual-line-mode 1))))

  ;; Don't split src window. 
  (setq org-src-window-setup 'current-window)

  (use-package org-indent
      :diminish org-indent-mode)

  (use-package htmlize
      :ensure t)

#+end_src

* Eshell
** Prompt
#+begin_src emacs-lisp
  (setq eshell-prompt-regexp "^[^αλ\n]*[αλ] ")
  (setq eshell-prompt-function
        (lambda nil
          (concat
           (if (string= (eshell/pwd) (getenv "HOME"))
               (propertize "~" 'face `(:foreground "#99CCFF"))
             (replace-regexp-in-string
              (getenv "HOME")
              (propertize "~" 'face `(:foreground "#99CCFF"))
              (propertize (eshell/pwd) 'face `(:foreground "#99CCFF"))))
           (if (= (user-uid) 0)
               (propertize " α " 'face `(:foreground "#FF6666"))
           (propertize " λ " 'face `(:foreground "#A6E22E"))))))

  (setq eshell-highlight-prompt nil)
#+end_src

** Aliases
#+begin_src emacs-lisp
  (defalias 'open 'find-file-other-window)
  (defalias 'clean 'eshell/clear-scrollback)
#+end_src

** Open files as root
#+begin_src emacs-lisp
  (defun eshell/sudo-open (filename)
    "Open a file as root in Eshell."
    (let ((qual-filename (if (string-match "^/" filename)
                             filename
                           (concat (expand-file-name (eshell/pwd)) "/" filename))))
      (switch-to-buffer
       (find-file-noselect
        (concat "/sudo::" qual-filename)))))
#+end_src

** Super-Control-RET to open Eshell
#+begin_src emacs-lisp
  (defun eshell-other-window ()
    "Create or visit an eshell buffer."
    (interactive)
    (if (not (get-buffer "*eshell*"))
        (progn
          (split-window-sensibly (selected-window))
          (other-window 1)
          (eshell))
      (switch-to-buffer-other-window "*eshell*")))

  (global-set-key (kbd "<s-C-return>") 'eshell-other-window)
#+end_src

* QoL
Quality-of-life modifications.
** 'y' or 'n' instead of 'yes' or 'no' when confirming
#+begin_src emacs-lisp
  (defalias 'yes-or-no-p 'y-or-n-p)
#+end_src

** Disable backup files
#+begin_src emacs-lisp
  (setq make-backup-file nil)
  (setq auto-save-default nil)
#+end_src

** Show line numbers
#+begin_src emacs-lisp
  (add-hook 'prog-mode-hook 'display-line-numbers-mode)
  (add-hook 'text-mode-hook 'display-line-numbers-mode)
#+end_src

** Show parent parentheses
#+begin_src emacs-lisp
  (show-paren-mode 1)
#+end_src

** Diable GUI elements
#+begin_src emacs-lisp
  (tool-bar-mode -1)
  (menu-bar-mode -1)
  (scroll-bar-mode -1)
#+end_src

** Enable copy-pasting outside of Emacs
#+begin_src emacs-lisp
  (setq x-select-enable-clipboard t)
#+end_src

** Disable the default startup screen
#+begin_src emacs-lisp
  (setq inhibit-startup-message t)
#+end_src

** Conservative scroll
When at the end of the "page", scroll just one line at a time.
#+begin_src emacs-lisp
  (setq scroll-conservatively 100)
#+end_src

** Disable ring bell sound
#+begin_src emacs-lisp
  (setq ring-bell-function 'ignore)
#+end_src

** Prettify symbols
#+begin_src emacs-lisp
  (global-prettify-symbols-mode t)
#+end_src

** Indentation
#+begin_src emacs-lisp
  (setq-default tab-width 4)
  (setq-default standard-indent 4)
  (setq c-basic-offset tab-width)
  (setq-default electric-indent-inhibit t)
  (setq-default indent-tabs-mode t)
  (setq backward-delete-char-untabify-method 'nil)
#+end_src

** Switches cursor automatically to new window
#+begin_src emacs-lisp
  (defun split-and-follow-horizontally ()
      (interactive)
      (split-window-below)
      (balance-windows)
      (other-window 1))
  (global-set-key (kbd "C-x 2") 'split-and-follow-horizontally)

  (defun split-and-follow-vertically ()
      (interactive)
      (split-window-right)
      (balance-windows)
      (other-window 1))
  (global-set-key (kbd "C-x 3") 'split-and-follow-vertically)
#+end_src

** Highlights current line
#+begin_src emacs-lisp
  (when window-system (global-hl-line-mode t))
#+end_src

** Bracket pair-matching
#+begin_src emacs-lisp
  (setq electric-pair-pairs '(
                              (?\{ . ?\})
                              (?\( . ?\))
                              (?\[ . ?\])
                              (?\" . ?\")
                              ))
  (electric-pair-mode t)
#+end_src

** Visiting the configuration
#+begin_src emacs-lisp
  (defun config-visit()
    (interactive)
    (find-file "~/.emacs.d/config.org"))
  (global-set-key (kbd "C-c e") 'config-visit)
#+end_src

** Reloading the configuration
#+begin_src emacs-lisp
  (defun config-reload ()
    "Reloads ~/.emacs.d/config.org at runtine"
    (interactive)
    (org-babel-load-file (expand-file-name "~/.emacs.d/config.org")))
  (global-set-key (kbd "C-c r") 'config-reload)
#+end_src

** Defer loading most packages for quicker startup times
#+begin_src emacs-lisp
  (setq use-package-always-defer t)
#+end_src

* General packages
** =diminish=
Hides minor modes to prevent clutter.
#+begin_src emacs-lisp
  (use-package diminish
    :ensure t)
#+end_src

** =which-key=
Helps you with commands -- it shows suggestions while you're typing.
#+begin_src emacs-lisp
  (use-package which-key
    :ensure t
    :init
    (which-key-mode))
#+end_src

** =evil=
Imports keybindings and some functionalities from Vi.
Useful if, like me, you've been a Vim user for some time.
#+begin_src emacs-lisp
  (use-package evil
    :ensure t
    :defer nil
    :init
    (setq evil-want-keybinding nil)
    (setq evil-want-C-u-scroll t)
    :config
    (evil-mode 1))
#+end_src

** =beacon=
Briefly highlights the cursor when switching windows/buffers.
#+begin_src emacs-lisp
  (use-package beacon
    :ensure t
    :init
    (beacon-mode 1))
#+end_src

** =auto-package-update=
Automatically updates packages (and removes old ones).
#+begin_src emacs-lisp
  (use-package auto-package-update
    :defer nil
    :ensure t
    :config
    (setq auto-package-update-delete-old-versions t)
    (setq auto-package-update-hide-results t)
    (auto-package-update-maybe))
#+end_src

** =ido=
Makes switching buffers and finding files more intuitive.
#+begin_src emacs-lisp
  (use-package ido
    :init
    (ido-mode 1)
    :config
    (setq ido-enable-flex-matching nil)
    (setq ido-create-new-buffer 'always)
    (setq ido-everywhere t))

  (use-package ido-vertical-mode
    :ensure t
    :init
    (ido-vertical-mode 1))

  (setq ido-vertical-define-keys 'C-n-and-C-p-only)
#+end_src

** =avy=
M-s <character> to move to the place of said <character> instead of moving the cursor to it.
It's hard to explain, but you'll use C-n and C-p way less.
#+begin_src emacs-lisp
   (use-package avy
      :ensure t
      :bind
      ("M-s" . avy-goto-char))
#+end_src

** =switch-window=
Don't keep using C-x o to switch windows anymore.
#+begin_src emacs-lisp
   (use-package switch-window
      :ensure t
      :config
      (setq switch-window-input-style 'minibuffer)
      (setq switch-window-increase 4)
      (setq switch-window-threshold 2)
      (setq switch-window-shortcut-style 'qwerty)
      (setq switch-window-qwerty-shortcuts
            '("a" "s" "d" "f" "j" "k" "l"))
      :bind
      ([remap other-window] . switch-window))
#+end_src

** =rainbow=
Highlights color hexadecimals with the appropriate color.
#+begin_src emacs-lisp
  (use-package rainbow-mode
    :ensure t
    :init (rainbow-mode 1))
#+end_src

** =powerline=
#+begin_src emacs-lisp
  (require 'powerline)
  (use-package powerline
     :ensure t
     :init
     (powerline-center-evil-theme)
     :hook
     ('after-init-hook) . 'powerline-reset)
#+end_src

* Programming
